### ISSUE TITLE
File renaming not storing in the database

### ISSUE THREAD

**Issue by ghost** [smoku/ecto_arc#1]
The below works to rename the file, but it does not rename what is stored in the database as the name of the file.

def filename(version, _) do
"#{UUID.uuid1()}"
end

The file name in the database remains the original file name, instead of the overridden version from the uuid above. 

If the filename and what is stored in the db differ, the system is broken. Carrierwave updates the db with the new overridden file name. Is it possible to do the same with arc_ecto?

I am using arc and arc_ecto. There is no sync between arc, arc_ecto and the db using def filename above.

**Comment by smoku** [comment]
Hi @AppyCat,

This project was made as a quick workaround because we were not satisfied with how arc_ecto works (especially the file upload during changeset casting). This project is not maintained and I will remove it from github soon. We developed a different library for handling uploads that we open sourced recently:

https://github.com/recruitee/bow
